export const modalSequence = [
    {
      id: 1,
      targetId: 'infomodal-button',
      headline: 'Welcome',
      borderRadius: '0 2vh 2vh 2vh',
      content: "Welcome to Paperbase! Use the arrow keys to take a tour through the application. You can go forward and backward, and you can exit the tour by closing this window. You can return to the tour anytime by clicking the <span class='material-icons infomodal-content-mi'>info</span> button on the left side of the screen. <span style='font-weight: 900;'>Additionally, every button and menu in this application has a tooltip description</span> that will appear when you hover over it. And finally, know that you can learn how Paperbase works simply by clicking around and seeing what happens. Don't worry; you can't break it. Have fun!",
    },
    {
      id: 2,
      targetId: 'viewpane',
      headline: '3D Canvas',
      borderRadius: '2vh 2vh 2vh 0',
      content: "Here, rendered in thousands of small cubes, is the entire collection of photographic paper samples. By default, each cube carries the base color of the paper sample it represents, though this mapping can be changed with the rightmost menu on the bottom of the screen. You can scroll to zoom and drag to pan. If you've zoomed or panned and want to reset the camera back to its default position, click the <span class='material-icons infomodal-content-mi'>flip_camera_ios</span> button above. <span style='font-weight: 900;'>If you click on a cube, information about the corresponding paper will appear in the selection panel.</span> Give it a try!",
    },
    {
      id: 3,
      targetId: 'multiClick',
      headline: 'Selection Panel',
      borderRadius: '0 2vh 2vh 2vh',
      content: "The buttons along the top of the screen control items in the selection panel. If you want to add multiple items to the panel, enter multiclick mode with <span class='material-icons infomodal-content-mi'>done_all</span>. Items can be selected by clicking or by dragging a box around them using the <span class='material-icons infomodal-content-mi'>highlight_alt</span> button just below. <span class='material-icons infomodal-content-mi'>delete_sweep</span> empties the panel; <span class='material-icons infomodal-content-mi'>file_download</span> downloads the data for your selection. <span class='material-icons infomodal-content-mi'>grid_view</span> changes the structure of the panel: list, grid, or small grid. <span class='material-icons infomodal-content-mi'>short_text</span> changes the amount of text on the screen; <span class='material-icons infomodal-content-mi'>format_size</span> changes the font size. The remaining buttons determine what fills the background of the panel tiles: <span class='material-icons infomodal-content-mi'>format_color_fill</span> the base color of the sample; <span class='material-icons infomodal-content-mi'>texture</span> a texture micrograph of the paper surface; <span class='material-icons infomodal-content-mi'>image</span> a thumbnail image of either the package or the sample book photograph; <span class='material-icons infomodal-content-mi'>fingerprint</span> an image of the backprint, if there is one; or <span class='material-icons infomodal-content-mi'>radar</span> a radar chart with color, gloss, roughness, and thickness axes.",
    },
    {
      id: 4,
      targetId: 'multiClick',
      headline: 'Detail Screen',
      borderRadius: '0 2vh 2vh 2vh',
      content: "You can only open the detail screen if there is at least one item in the selection panel. When you hover over the lower right hand corner of a panel item, you'll see a <span class='material-icons infomodal-content-mi'>open_in_full</span>, which opens the detail screen for that panel item. <span style='font-weight: 900'>The rest of this tour stop will make more sense if you do that now, so give it a shot...</span><br><br>Ok, you should now be looking at a detail screen, and the detail image you are seeing is determined by whichever asset was chosen to fill the panel tile&mdash;the package or sample book image, the texure image, or the backprint. If there is more than one item in the panel, the left and right arrow keys will page through them, and if you are seeing a package image, you can usually switch between recto and verso sides of the package, and sometimes even tops, bottoms, and sides, using the up and down arrows.<br><br>Any detail screen image can be clicked to open a fullsize version in a new browser tab. There are additional buttons along the left side of the detail screen, although depending on which item you've selected, you may only be seeing <span class='material-icons infomodal-content-mi'>flare</span>, which links out to the item record in Yale's cross-collections discovery tool, LUX. If the detail screen item has a backprint, you'll see a clickable <span class='material-icons infomodal-content-mi'>fingerprint</span>, which opens the fullsize backprint image in a new tab. If we have processing instructions for the item, you'll see a <span class='material-icons infomodal-content-mi'>science</span>, which opens the instructions in your browser's PDF viewer.<br><br><span style='font-weight: 900'>Ok, now let's close <span class='material-icons infomodal-content-mi'>cancel</span> the detail screen before we move on...</span>",
    },
    {
      id: 5,
      targetId: 'glyphControls',
      headline: '3D Glyphs',
      borderRadius: '2vh 0 2vh 2vh',
      content: "The default glyph is a simple cube <span class='material-icons infomodal-content-mi'>square</span>, but you can also choose a cube <span class='material-icons infomodal-content-mi'>aspect_ratio</span> whose size is determined by the expressiveness of the paper it represents&mdash;small cubes are less expressive (thin, glossy, smooth, and white), and large cubes are more expressive (thick, matte, rough, and warm-toned); a box <span class='material-icons infomodal-content-mi'>line_weight</span> whose height is determined by the thickness of the paper sample it represents; and a 3D radar chart <span class='material-icons infomodal-content-mi'>radar</span> with color, gloss, roughness, and thickness axes.",
    },
    {
      id: 6,
      targetId: 'plottypeControls',
      headline: 'Plot Types',
      borderRadius: '2vh 0 2vh 2vh',
      content: "The default plot type is a grid <span class='material-icons infomodal-content-mi'>apps</span>, but you can also choose a histogram <span class='material-icons infomodal-content-mi'>bar_chart</span>, which shows the distribution of a single data variable; a scatterplot <span class='material-icons infomodal-content-mi'>grain</span>, which shows the relationship between two variables; a cluster plot <span class='material-icons infomodal-content-mi'>bubble_chart</span>, which arranges the items into clusters and plots similar clusters together; or a texture map <span class='material-icons infomodal-content-mi'>map</span>, which represents the landscape of paper textures.",
    },
    {
      id: 7,
      targetId: 'bottomControls',
      headline: 'Axis Menus',
      borderRadius: '2vh 2vh 2vh 0',
      content: "You can map data variables to plot axes using the axis menus. From left to right, they are the <i>x</i>, <i>y</i>, and <i>z</i> axes of the 3D canvas. In a grid, only the <i>x</i>-axis is active, and it determines the sorting order of the grid items. In a histogram, the <i>x</i>-axis is the variable whose distribution is binned and plotted along the horizontal, and the <i>y</i>-axis determines the vertical sorting order of the columns. In a scatterplot, all three axes can be active, although only two are required. The axis menu settings are idle for both the cluster plot and the texture map. <span style='font-weight: 900'>There is, additionally, a fourth menu, that maps a data variable to the color of the plot items.</span>",
    },
    {
      id: 8,
      targetId: 'spreadControls',
      headline: 'Plot Spread',
      borderRadius: '2vh 0 2vh 2vh',
      content: "This slider controls the plot's degree of spread, which means slightly different things in each case. If the plot is a grid, the slider controls the number of columns; if it is a histogram, it controls the number of bins; in a scatterplot, it controls the visual length of the axes; and in a cluster plot, it determines the tightness of the cluster packing. The slider settings are idle for the texture map.",
    },
    {
      id: 9,
      targetId: 'filterControls',
      headline: 'Filters',
      borderRadius: '2vh 2vh 0 2vh',
      content: "The filter button <span class='material-icons infomodal-content-mi'>filter_alt</span> opens and closes the filter panel. After selecting filters, you can clear all filters with <span class='material-icons infomodal-content-mi'>filter_alt_off</span>. <span class='material-icons infomodal-content-mi'>file_download</span> downloads the filtered data.<br><br><span style='font-weight: 900'>Ok, let's open the filter panel and expand it by clicking <span class='material-icons infomodal-content-mi'>chevron_left</span>.</span> The panel is divided into filter groups, each one associated with some variable in the data. In each group is a bank of buttons whose colors reflect the relative frequencies of the values they represent; higher frequencies are darker.<br><br>Clicking a button will apply the filter to the data, and any items that fail to satisfy the filter will be backgrounded in the 3D canvas, usually by dimming. When a filter is applied, all other filter buttons in the panel update their colors to represent their frequencies in the now filtered data. You can click any number of filters, and additionally, you can filter the data along continuous variables like gloss, thickness, and fluorescence using filter sliders.<br><br>If you'd like to add your filter to the selection panel, click <span class='material-icons infomodal-content-mi'>queue</span>; if you'd like your filter to replace the current selection, click <span class='material-icons infomodal-content-mi'>open_in_new</span>.",
    },
  ];