export const landingText = {
    s1: {
        title: 'THE COLLECTION',
        subtitle: 'Our reference collection of gelatin silver photographic papers.',
        text: [
            `Throughout the twentieth century, photography was fundamentally a paper-based medium, and photographic papers have played a crucial role in shaping the medium's history and practice. However, little research has been done on how the material, technical, and visual properties of these papers impacted the work of photographers. This lack of scholarly attention stems partly from the difficulty of accessing and analyzing the physical characteristics of historical photographic papers.`,
            `To address this gap, the Lens Media Lab at Yale University's Institute for the Preservation of Cultural Heritage has undertaken an extensive project to document and characterize its collection of over 7,500 dated and identified gelatin silver papers manufactured between 1890 and 2010. This is believed to be the largest collection of photographic paper samples in the world. Roughly one-third of the samples in the collection come from packages of photographic paper; the remaining two-thirds come from sample books published by manufacturers, and most of the samples in these books are printed photographs. From this collection, the lab has constructed a rich and comprehensive dataset that combines traditional catalog information with extensive material analyses.`,
            `The dataset includes, for each paper sample, detailed measurements of surface texture, gloss, base color, image color, thickness, and fluorescence to delineate the wide material variety of papers used by both professional and amateur photographers during the twentieth century. Also recorded for each paper sample are the manufacturer, brand, surface code, spatial dimensions, and year of manufacture (sometimes estimated or inferred); any resin coatings, toning agents, backprints, and processing instructions; and any language used by the manufacturer to describe the material properties that we measure: texture terms like “smooth”, “rough”, and “pebbled”; color terms like “white”, “cream”, and “ivory”; reflectance terms like “glossy”, “matte”, and “luster”; and designations of paper thickness, usually “single weight” or “double weight”. The lab has done extensive imaging of the collection as well, including microscopic images of the paper surfaces; high-resolution digital images of any paper packages, sample book photographs, and backprints; and scans of any processing instructions. This rich trove of data is now made publicly accessible through Paperbase, a new web-based research platform developed by the Lens Media Lab.`,
            `By providing access to this unique dataset through Paperbase, the Lens Media Lab seeks to catalyze new approaches to characterizing the material practices of twentieth-century photographers. Moreover, Paperbase will enable researchers to chart the evolution of paper-based photographic technologies, such as the introduction of optical brightening agents and resin coatings, and to better understand how the language used to describe photographic papers, including widespread terms like “white” and “glossy,” changed over time.`
        ] 
    },
    s2: {
        title: 'METHODS',
        subtitle: 'How we built the collection and the dataset.',
        text: [
            `For loose prints, thickness is measured with a calipers-style micrometer; ours is a Mitutoyo ABSOLUTE Digimatic. For mounted prints, we use a Mitutoyo ABSOLUTE Digimatic depth gauge. Thickness is measured in millimeters (mm), and photographic papers typically fall somewhere between 0.05 and 0.5 mm. We take 3 thickness measurements per print and generally take the median (rather than the mean) as the representative measurement, to mitigate the impact of extreme outliers and anomalies.`,
            `Gloss is measured using a glossmeter and in gloss units (GU), an industry standard. Our glossmeter is a BYK-Gardner micro-TRI-gloss, which measures specular reflection at 20°, 60°, and 85° angles. We generally consider only the 60° angle, as most photographic papers fall within a range of gloss values well-suited to this angle—values generally between 1-100 GU. As with thickness, we take 3 gloss measurements for every print and use the median.`,
            `We measure the color of both the paper base and the silver image material using a spectrophotometer. In this study, the prints were measured with X-Rite spectrophotometers, which use the 2° observer and the d65 illuminant. A separate ultraviolet (UV) illuminant can also be used.`,
            `For the purposes of our expressiveness model, we focus on paper roughness, a property well-defined in the surface metrology literature and measurable directly using an optical profilometer. Roughness is, approximately, the standard deviation of heights of the paper surface. The greater the variation in surface heights, the rougher the surface.`,
        ]
    }
}